export const ipcChannels = {
	projectsList: "projects:list",
	projectsAdd: "projects:add",
	projectsRemove: "projects:remove",
	projectsChanged: "projects:changed",
	filesList: "files:list",
	filesOpen: "files:open",
	filesShowInFolder: "files:show-in-folder",
	sessionsList: "sessions:list",
	sessionsRename: "sessions:rename",
	settingsGet: "settings:get",
	settingsUpdate: "settings:update",
	settingsApplyWindow: "settings:apply-window",
	gitBranches: "git:branches",
	gitCheckout: "git:checkout",
	piCheck: "pi:check",
	appInfo: "app:info",
	appOpenExternal: "app:open-external",
	agentsList: "agents:list",
	agentsCreate: "agents:create",
	agentsStop: "agents:stop",
	agentsPrompt: "agents:prompt",
	agentsAbort: "agents:abort",
	agentsExportHtml: "agents:export-html",
	agentsReload: "agents:reload",
	agentsRestart: "agents:restart",
	agentsCompact: "agents:compact",
	agentsForkMessages: "agents:fork-messages",
	agentsFork: "agents:fork",
	agentsRuntimeState: "agents:runtime-state",
	agentsCycleModel: "agents:cycle-model",
	agentsAvailableModels: "agents:available-models",
	agentsSetModel: "agents:set-model",
	agentsCycleThinking: "agents:cycle-thinking",
	agentsSetThinking: "agents:set-thinking",
	agentsState: "agents:state",
	agentsEvent: "agents:event",
	agentsMessage: "agents:message",
	agentsLog: "agents:log",

	/** 流式思考内容更新，agent 忙碌时实时推送当前思考文本 */
	agentsThinking: "agents:thinking",

	configGetModels: "config:get-models",
	configGetAuth: "config:get-auth",
	configGetSettings: "config:get-settings",
	configSaveModels: "config:save-models",
	configSaveAuth: "config:save-auth",
	configSaveSettings: "config:save-settings",
	configSaveRaw: "config:save-raw",

	/** 切换开发者控制台 */
	appToggleDevTools: "app:toggle-devtools",

	/** RPC 日志，用于调试 */
	agentsRpcLog: "agents:rpc-log",
} as const;
